//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModel_using_the_Entity_Data_Model_Wizard
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionDetail
    {
        public long DetailId { get; set; }
        public long TransactionId { get; set; }
        public string Vendor { get; set; }
        public string ItemOperation { get; set; }
    
        public virtual Transaction Transaction { get; set; }
    }
}
